### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([22,23,33, 42, 57])
print(a)

[22 23 33 42 57]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]


In [4]:
#shape
print(a.shape)
# print(b.shape) # 2 is for rows and 3 is for cols
print(c.shape)

(5,)
(3, 2, 2)


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
a.dtype

dtype('int64')

In [7]:
# np.arange
# Create an array of values from 1 to 9 (exclusive)

np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(1,10,4) # 2 is for step size

array([1, 5, 9])

In [9]:
# with reshape
np.arange(16)
np.arange(8).reshape(2,2,2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# np.ones and np.zeros
# in neural networks we can intialize the weights by using np.ones or np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# np.random
np.random.random((3,4))

array([[0.269303  , 0.7602029 , 0.922165  , 0.74608959],
       [0.14956245, 0.65179997, 0.45436747, 0.0369877 ],
       [0.39482103, 0.0814415 , 0.15849699, 0.87162633]])

In [13]:
# np.linspace
np.linspace(-10,10,8,dtype=int) # provide three things, first one is the lower range, upper range, and the number of elements to linearly generate.
#np.linspace(-10,10,10)

array([-10,  -8,  -5,  -2,   1,   4,   7,  10])

In [14]:
# np.identity
#diagonal elements are 1 and rest of the elements are zeros
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [15]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# ndim
# It is used for dimension, 1 is 1D , 2 is for 2D and 3 is for 3D
a3.ndim

3

In [17]:
# shape
# how many rows and cols in an array.
print(a2.shape)
a2
#3D arrays is a combination of 2D array.
#a3 has 2 elements(each element is of 2D array.)
# and every 2d array shape is of 2,2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
# size
# no. of elements in an array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int64
float64
int64


### Changing Datatype

In [20]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational
a2 = np.arange(12,24).reshape(3,4)
print(a2)
a2 == 15

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Indexing and Slicing

In [25]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a1[0] # to access the first element
a1[-1] # to access the last element
# two types of indexing. Positive and negative
# Positive indexing starts from 0 and move from left to right.

np.int64(9)

In [28]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# to extract 5 from this 2d array. what to do?
a2[1,1]

np.int64(5)

In [30]:
a2[1,0]

np.int64(4)

In [31]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a3[1,0,1]

np.int64(5)

In [33]:
a3[1,1,0]

np.int64(6)

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
#slicing is used to extract multiple elements
# we want to extarct first row from a2.
# first specify which row u want, colon is for all elements
a2[1,]

array([4, 5, 6, 7])

In [36]:
a2[:,2] # all row elements from 3rd col

array([ 2,  6, 10])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# extract 17,18,21,22 from a2
# which rows and which cols.
# 1: as we need 1st and 2nd row
# for col we need 1 and 2nd col
# 1:3 , 3 is exclusive so 1 and 2 col elements will be extracted.
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [39]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
a3[1,1,:]

array([12, 13, 14])

In [43]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [44]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [45]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [48]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [49]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [50]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
